version: "3"

services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pigeon
      - MONGO_INITDB_ROOT_PASSWORD=mongodb_password

  server:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - db
    env_file: .env
    environment:
      - PORT=3001
      - MONGO_DB_URI=mongodb://pigeon:mongodb_password@db/pigeon?authSource=admin

volumes:
  db-data:
